In [1]:
# Importing dependencies
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
# Reading the data into a Pandas DataFrame
natural_disaster_df = pd.read_excel('Resources/public_emdat_2004_to_2024.xlsx')
natural_disaster_df.head(10)

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,Country,Subregion,Region,Location,Origin,Associated Types,OFDA/BHA Response,Appeal,Declaration,AID Contribution ('000 US$),Magnitude,Magnitude Scale,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,Entry Date,Last Update
0,2004-0001-IDN,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp000cgss,NaN,IDN,Indonesia,South-eastern Asia,Asia,"Kota Mataram, Lombok Barat districts (Nusateng...",NaN,NaN,No,No,No,NaN,5.8,Moment Magnitude,-8.310,115.788,NaN,2004,1.0,1.0,2004,1.0,1.0,1.0,40.0,30000.0,NaN,30040.0,NaN,NaN,NaN,NaN,12000.0,19358.0,61.989586,"[{""adm2_code"":17974,""adm2_name"":""Karangasem""},...",2014-02-25,2023-09-25
1,2004-0004-ASM,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Heta,ASM,American Samoa,Polynesia,Oceania,American Samoa,NaN,NaN,No,No,Yes,NaN,310.0,Kph,NaN,NaN,NaN,2004,1.0,5.0,2004,1.0,5.0,NaN,60.0,20000.0,3000.0,23060.0,NaN,NaN,NaN,NaN,150000.0,241976.0,61.989586,"[{""adm1_code"":389,""adm1_name"":""Administrative ...",2005-07-28,2023-09-25
2,2004-0004-NIU,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Heta,NIU,Niue,Polynesia,Oceania,Alofi area (Niue province),NaN,NaN,No,No,No,NaN,300.0,Kph,NaN,NaN,NaN,2004,1.0,6.0,2004,1.0,6.0,1.0,2.0,200.0,500.0,702.0,NaN,NaN,NaN,NaN,40000.0,64527.0,61.989586,"[{""adm1_code"":2241,""adm1_name"":""Administrative...",2004-01-08,2023-09-25
3,2004-0004-TON,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Heta,TON,Tonga,Polynesia,Oceania,"Tafahi, Nuiatoputapu islands (Tonga province)",NaN,NaN,No,No,No,NaN,NaN,Kph,NaN,NaN,NaN,2004,1.0,6.0,2004,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm1_code"":2976,""adm1_name"":""Administrative...",2004-01-13,2023-09-25
4,2004-0004-WSM,No,nat-met-sto-tro,Natural,Meteorological,Storm,Tropical cyclone,NaN,Heta,WSM,Samoa,Polynesia,Oceania,"Savaii, Upolu islands (Samoa province)",NaN,Flood|Surge,No,No,Yes,NaN,310.0,Kph,NaN,NaN,NaN,2004,1.0,5.0,2004,1.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm1_code"":2618,""adm1_name"":""Administrative...",2004-01-16,2023-09-25
5,2004-0006-BDI,No,nat-met-sto-sto,Natural,Meteorological,Storm,Storm (General),NaN,NaN,BDI,Burundi,Sub-Saharan Africa,Africa,Mpanda district (Bubanza province),NaN,NaN,No,No,No,NaN,NaN,Kph,NaN,NaN,NaN,2004,1.0,4.0,2004,1.0,4.0,NaN,NaN,NaN,500.0,500.0,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm2_code"":40561,""adm2_name"":""Mpanda""}]",2004-01-07,2023-09-25
6,2004-0010-TUR,No,nat-met-ext-col,Natural,Meteorological,Extreme temperature,Cold wave,NaN,NaN,TUR,Türkiye,Western Asia,Asia,"Aragpir city (Malatya province), Istanbul, Ank...",NaN,Snow/ice,No,No,No,NaN,-22.0,°C,NaN,NaN,NaN,2004,1.0,9.0,2004,1.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm1_code"":3023,""adm1_name"":""Ankara""},{""adm...",2004-01-12,2023-09-25
7,2004-0011-DZA,No,nat-geo-ear-gro,Natural,Geophysical,Earthquake,Ground movement,USGS:usp000chm5,NaN,DZA,Algeria,Northern Africa,Africa,"Alger, Boumerdes provinces",NaN,NaN,No,No,No,NaN,4.5,Moment Magnitude,36.852,3.418,NaN,2004,1.0,10.0,2004,1.0,10.0,NaN,300.0,NaN,NaN,300.0,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm1_code"":344,""adm1_name"":""Alger""},{""adm1_...",2014-03-26,2023-09-25
8,2004-0012-IRN,No,nat-hyd-flo-fla,Natural,Hydrological,Flood,Flash flood,NaN,NaN,IRN,Iran (Islamic Republic of),Southern Asia,Asia,"Firuzabad, Lamerd, Darab, Abadeh, Bavanat, Mam...",Heavy rains,Broken Dam/Burst bank,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2004,1.0,10.0,2004,1.0,19.0,6.0,10.0,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm1_code"":1540,""adm1_name"":""Bushehr""},{""ad...",2004-02-04,2023-09-25
9,2004-0012-IRQ,No,nat-hyd-flo-fla,Natural,Hydrological,Flood,Flash flood,NaN,NaN,IRQ,Iraq,Western Asia,Asia,"Marshland area (Nassriya district, Thi-Qar pro...",Heavy rains,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2004,1.0,10.0,2004,1.0,19.0,NaN,NaN,8000.0,NaN,8000.0,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,"[{""adm2_code"":36844,""adm2_name"":""Nassriya""}]",2004-02-04,2023-09-25

In [3]:
#Info on columns
natural_disaster_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7692 entries, 0 to 7691
Data columns (total 46 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DisNo.                                     7692 non-null   object
 1   Historic                                   7692 non-null   object
 2   Classification Key                         7692 non-null   object
 3   Disaster Group                             7692 non-null   object
 4   Disaster Subgroup                          7692 non-null   object
 5   Disaster Type                              7692 non-null   object
 6   Disaster Subtype                           7692 non-null   object
 7   External IDs                               2090 non-null   object
 8   Event Name                                 1464 non-null   object
 9   ISO                                        7692 non-null   object
 10  Country                                    7692 non-null   object
 11  Subregion                                  7692 non-null   object
 12  Region                                     7692 non-null   object
 13  Location                                   7413 non-null   object
 14  Origin                                     3354 non-null   object
 15  Associated Types                           2985 non-null   object
 16  OFDA/BHA Response                          7692 non-null   object
 17  Appeal                                     7692 non-null   object
 18  Declaration                                7692 non-null   object
 19  AID Contribution ('000 US$)                310 non-null    float64
 20  Magnitude                                  2514 non-null   float64
 21  Magnitude Scale                            7189 non-null   object
 22  Latitude                                   1671 non-null   float64
 23  Longitude                                  1671 non-null   float64
 24  River Basin                                982 non-null    object
 25  Start Year                                 7692 non-null   int64
 26  Start Month                                7648 non-null   float64
 27  Start Day                                  6915 non-null   float64
 28  End Year                                   7692 non-null   int64
 29  End Month                                  7615 non-null   float64
 30  End Day                                    6904 non-null   float64
 31  Total Deaths                               5469 non-null   float64
 32  No. Injured                                2202 non-null   float64
 33  No. Affected                               5134 non-null   float64
 34  No. Homeless                               885 non-null    float64
 35  Total Affected                             6143 non-null   float64
 36  Reconstruction Costs ('000 US$)            30 non-null     float64
 37  Reconstruction Costs, Adjusted ('000 US$)  30 non-null     float64
 38  Insured Damage ('000 US$)                  596 non-null    float64
 39  Insured Damage, Adjusted ('000 US$)        586 non-null    float64
 40  Total Damage ('000 US$)                    2565 non-null   float64
 41  Total Damage, Adjusted ('000 US$)          2531 non-null   float64
 42  CPI                                        7467 non-null   float64
 43  Admin Units                                6893 non-null   object
 44  Entry Date                                 7692 non-null   object
 45  Last Update                                7692 non-null   object
dtypes: float64(20), int64(2), object(24)
memory usage: 2.7+ MB

In [4]:
#Get unique values in the Disaster Type and Disaster Subtype columns
disaster_type = natural_disaster_df['Disaster Type'].unique()
disaster_subtype = natural_disaster_df['Disaster Subtype'].unique()

print(disaster_type)
print(disaster_subtype)

['Earthquake' 'Storm' 'Extreme temperature' 'Flood' 'Volcanic activity'
 'Mass movement (wet)' 'Wildfire' 'Mass movement (dry)' 'Drought'
 'Glacial lake outburst flood']
['Ground movement' 'Tropical cyclone' 'Storm (General)' 'Cold wave'
 'Flash flood' 'Riverine flood' 'Blizzard/Winter storm' 'Ash fall'
 'Landslide (wet)' 'Severe weather' 'Mudslide' 'Tornado' 'Forest fire'
 'Hail' 'Lightning/Thunderstorms' 'Heat wave' 'Avalanche (wet)'
 'Flood (General)' 'Landslide (dry)' 'Tsunami'
 'Land fire (Brush, Bush, Pasture)' 'Drought' 'Extra-tropical storm'
 'Severe winter conditions' 'Wildfire (General)' 'Coastal flood'
 'Rockfall (dry)' 'Sand/Dust storm' 'Rockfall (wet)' 'Avalanche (dry)'
 'Volcanic activity (General)' 'Lava flow' 'Storm surge' 'Derecho'
 'Pyroclastic flow' 'Glacial lake outburst flood' 'Lahar']

In [5]:
#Drop unwanted columns   
natural_disaster_df = natural_disaster_df.drop(columns=['Historic','Classification Key','Disaster Group','Disaster Subgroup',
                                                        'External IDs','ISO','Location','Admin Units'])
natural_disaster_df.head()

,DisNo.,Disaster Type,Disaster Subtype,Event Name,Country,Subregion,Region,Origin,Associated Types,OFDA/BHA Response,Appeal,Declaration,AID Contribution ('000 US$),Magnitude,Magnitude Scale,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Entry Date,Last Update
0,2004-0001-IDN,Earthquake,Ground movement,NaN,Indonesia,South-eastern Asia,Asia,NaN,NaN,No,No,No,NaN,5.8,Moment Magnitude,-8.31,115.788,NaN,2004,1.0,1.0,2004,1.0,1.0,1.0,40.0,30000.0,NaN,30040.0,NaN,NaN,NaN,NaN,12000.0,19358.0,61.989586,2014-02-25,2023-09-25
1,2004-0004-ASM,Storm,Tropical cyclone,Heta,American Samoa,Polynesia,Oceania,NaN,NaN,No,No,Yes,NaN,310.0,Kph,NaN,NaN,NaN,2004,1.0,5.0,2004,1.0,5.0,NaN,60.0,20000.0,3000.0,23060.0,NaN,NaN,NaN,NaN,150000.0,241976.0,61.989586,2005-07-28,2023-09-25
2,2004-0004-NIU,Storm,Tropical cyclone,Heta,Niue,Polynesia,Oceania,NaN,NaN,No,No,No,NaN,300.0,Kph,NaN,NaN,NaN,2004,1.0,6.0,2004,1.0,6.0,1.0,2.0,200.0,500.0,702.0,NaN,NaN,NaN,NaN,40000.0,64527.0,61.989586,2004-01-08,2023-09-25
3,2004-0004-TON,Storm,Tropical cyclone,Heta,Tonga,Polynesia,Oceania,NaN,NaN,No,No,No,NaN,NaN,Kph,NaN,NaN,NaN,2004,1.0,6.0,2004,1.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,2004-01-13,2023-09-25
4,2004-0004-WSM,Storm,Tropical cyclone,Heta,Samoa,Polynesia,Oceania,NaN,Flood|Surge,No,No,Yes,NaN,310.0,Kph,NaN,NaN,NaN,2004,1.0,5.0,2004,1.0,5.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61.989586,2004-01-16,2023-09-25